### PR TITLE
Store package stylesheets in the styles/ directory

### LINKED ISSUE #10: Package.getStylesheetsPath is deprecated.
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `pep8` package
```
ThemePackage.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app/src/package.js:430:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:434:35)
```

### PR DESCRIPTION
**Pull request by oconnormi**
resolves #10

[Review on Reviewable](https://reviewable.io/reviews/rnhmjoj/solarized-dark-ui/23)

### CODE REVIEW

**Comment by oconnormi** [comment]
@rnhmjoj, Is anyone maintaining this still. I have noticed from another issue that you are no longer using atom and therefore aren't planning on publishing updates yourself. If no one else is going to publish updates I'd be happy to contribute / take over maintenance of this package

**Comment by rnhmjoj** [comment]
Great! I am making you a collaborator.

**Comment by rnhmjoj** [comment]
To publish new versions I have to give you my api key.
Is this your pgp key fingerprint `FE73 2E7C C59A 4287 3E36  66D3 E071 D16C 04DC 7CBB`?

**Comment by oconnormi** [comment]
yep that's me :smile:

**Comment by oconnormi** [comment]
@rnhmjoj Looks like I'm able to publish versions as long as I have write access to this repo actually

**Comment by rnhmjoj** [comment]
Ah, cool.

**Pull request merged**
